name = "r2-vod-frontend"
main = "src/index.ts" # This is a placeholder, Pages Functions don't use a 'main' entry
compatibility_date = "2023-12-18" # Use a recent compatibility date

[vars]
# You can define environment variables here if needed

[[r2_buckets]]
binding = "R2_BUCKET" # This is the name you'll use in your Pages Function to access the R2 bucket
bucket_name = "dance" # Replace with your actual R2 bucket name

[build]
pages_build_output_dir = ".next"